version: "3"

services:

  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: test-covid.loc
      MYSQL_USER: "test-covid"
      MYSQL_PASSWORD: "!Test-Covid_1"